// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: fiboslicer.proto

package fiboslicer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FiboSlicerClient is the client API for FiboSlicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiboSlicerClient interface {
	GetFibonacciSlice(ctx context.Context, in *SliceRequest, opts ...grpc.CallOption) (*FibonacciSliceResponse, error)
}

type fiboSlicerClient struct {
	cc grpc.ClientConnInterface
}

func NewFiboSlicerClient(cc grpc.ClientConnInterface) FiboSlicerClient {
	return &fiboSlicerClient{cc}
}

func (c *fiboSlicerClient) GetFibonacciSlice(ctx context.Context, in *SliceRequest, opts ...grpc.CallOption) (*FibonacciSliceResponse, error) {
	out := new(FibonacciSliceResponse)
	err := c.cc.Invoke(ctx, "/fiboslicer.FiboSlicer/GetFibonacciSlice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FiboSlicerServer is the server API for FiboSlicer service.
// All implementations must embed UnimplementedFiboSlicerServer
// for forward compatibility
type FiboSlicerServer interface {
	GetFibonacciSlice(context.Context, *SliceRequest) (*FibonacciSliceResponse, error)
	mustEmbedUnimplementedFiboSlicerServer()
}

// UnimplementedFiboSlicerServer must be embedded to have forward compatible implementations.
type UnimplementedFiboSlicerServer struct {
}

func (UnimplementedFiboSlicerServer) GetFibonacciSlice(context.Context, *SliceRequest) (*FibonacciSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFibonacciSlice not implemented")
}
func (UnimplementedFiboSlicerServer) mustEmbedUnimplementedFiboSlicerServer() {}

// UnsafeFiboSlicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiboSlicerServer will
// result in compilation errors.
type UnsafeFiboSlicerServer interface {
	mustEmbedUnimplementedFiboSlicerServer()
}

func RegisterFiboSlicerServer(s grpc.ServiceRegistrar, srv FiboSlicerServer) {
	s.RegisterService(&FiboSlicer_ServiceDesc, srv)
}

func _FiboSlicer_GetFibonacciSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiboSlicerServer).GetFibonacciSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fiboslicer.FiboSlicer/GetFibonacciSlice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiboSlicerServer).GetFibonacciSlice(ctx, req.(*SliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FiboSlicer_ServiceDesc is the grpc.ServiceDesc for FiboSlicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FiboSlicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fiboslicer.FiboSlicer",
	HandlerType: (*FiboSlicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFibonacciSlice",
			Handler:    _FiboSlicer_GetFibonacciSlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fiboslicer.proto",
}
